# -*- coding: utf-8 -*-
"""Hangman Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRsYK5LF069Iyt-N_yyooi_ywnmVFYew
"""

import random

words = ["python", "coding", "computer", "programming"]
word = random.choice(words)

guessed = []
attempts = 6

while attempts > 0:
    display = ""

    for letter in word:
        if letter in guessed:
            display += letter
        else:
            display += "_"

    print(display)

    if "_" not in display:
        print("You win!")
        break

    guess = input("Guess a letter: ")

    if guess in word:
        guessed.append(guess)
    else:
        attempts -= 1
        print("Wrong! Attempts left:", attempts)